### ISSUE TITLE
Missing player features and signs

### ISSUE THREAD

**Issue by nadavgut** [kulek1/guitar-tab-maker-issues#6]
Hi

1. When I write 14b15, for some string, in the player we don't hear actual bending, this is relevant to other signs as well among them slide down and up and pull off and hammer ons.
2. It would also be very nice if you could add a vibrato sign.

**Comment by kulek1** [comment]
Hi there,

1. Playback doesn't support custom notes at all, and it's on my "nice-to-have" list because it's quite a time-consuming feature to implement. Nevertheless, I am open to reconsidering this when there is more interest in this functionality.
2. The new vibrato symbol has been released in v2.4.0 :)

Closing this as it's partially resolved.
