### ISSUE TITLE
Save tuning not working

### ISSUE THREAD

**Issue by Kopplog** [kulek1/guitar-tab-maker-issues#75]
Save Tuning haven't worked so far twice.

I tried to save tuning of a customized 10-string-tuning without success. So, all strings have been retuned beforehand.

**Comment by kulek1** [comment]
@Kopplog what do you mean by saying "Save tuning"? I don't believe there's an option to save permanently any custom tunings

**Comment by Kopplog** [comment]
Hi Mateusz,
I'm terribly sorry...

Maybe I did misinterpret your Apps functionality (see Screenshots
attached), as I expected it to be necessary to save my custom tuning after
tuning each of my 10 strings.

Forgive me, but may I ask you if you intended of implementing such feature
in the near future, or does it make more sense if I'd rather ask you to
implement my 10-string-tuning? (IMHO, as an application designer myself,
giving customers the ability to fully customize string count, tuning and
saving those would bring more customers by, same-time, easen your customer
support).

Have a wonderful day,

Chris

**Comment by kulek1** [comment]
Hey, unfortunately I don't see any screenshots attached.

When it comes to custom tunings then there are 2 options so far:
1. Customising the tuning the way you want without saving it as new tuning by clicking on the open notes:
<img width="134" alt="Screenshot 2024-10-06 at 18 45 23" src="https://github.com/user-attachments/assets/05e48f69-2db4-4c92-8cf7-f23aefdb5521">

2. Requesting a new tuning that will be added to the app for everyone. 


> (IMHO, as an application designer myself,
giving customers the ability to fully customize string count, tuning and
saving those would bring more customers by, same-time, easen your customer
support

My view is that the number of tuning combinations is finite, and adding them to the app benefits all users because they don't have to do it manually every time. If I add an option to save custom tunings, users are less likely to report it as a feature request, so I'm happy to add new custom tunings for 10-string instruments.
